[package]
name = "exalt-account-manager"
version = "4.0.0"
description = "Exalt Account Manager"
authors = ["MaikEight"]
license = "GPL-3.0 license"
repository = "https://github.com/MaikEight/ExaltAccountManager"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.5.1", features = [] }

[dependencies]
tauri = { version = "1.5", features = [ "updater", "dialog-all", "http-all", "devtools", "path-all", "macos-private-api", "window-set-min-size", "window-unminimize", "window-unmaximize", "window-start-dragging", "window-close", "window-minimize", "window-hide", "window-show", "window-maximize", "fs-all", "shell-open"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
async-std = "1.12"
window-vibrancy = "0.4.3"
dirs = "3.0.2"
md5 = "0.7.0"
tokio = "1.35.1"
futures = "0.3.29"
flate2 = "1.0.28"
walkdir = "2.4.0"
reqwest = { version = "0.11", features = ["blocking"] }
zip = "0.6.6"
mpsc = "0.2.3"
anyhow = "1.0"
curl = "0.4"
wmi = "0.13.1"
sha1 = "0.10.6"
winapi = { version = "0.3.9", features = ["winnt", "processthreadsapi", "securitybaseapi", "handleapi", "sddl", "dpapi", "wincrypt"] }
num-bigint = "0.4.2"
num-traits = "0.2.14"
hex = "0.4.3"
diesel = { version = "2.1.5", features = ["sqlite", "r2d2", "64-column-tables"] }
diesel_migrations = "2.1.0"
diesel_derives = "2.1.3"
libsqlite3-sys = { version = "*", features = ["bundled"] }
lazy_static = "1.4.0"
uuid = "1.7.0"
base64 = "0.22.0"
eam_commons = { path = "../src-modules/eam_commons" }
h2 = "0.4.3"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
