[package]
name = "exalt-account-manager"
version = "4.2.0"
description = "Exalt Account Manager"
authors = ["MaikEight"]
license = "GPL-3.0 license"
repository = "https://github.com/MaikEight/ExaltAccountManager"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.5.4", features = [] }

[dependencies]
tauri = { version = "1.7.2", features = [ "process-all", "updater", "dialog-all", "http-all", "devtools", "path-all", "macos-private-api", "window-set-min-size", "window-unminimize", "window-unmaximize", "window-start-dragging", "window-close", "window-minimize", "window-hide", "window-show", "window-maximize", "fs-all", "shell-open"] }
devtools = "0.3.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
async-std = "1.13"
window-vibrancy = "0.4.0"
dirs = "5.0.1"
md5 = "0.7.0"
tokio = "1.40.0"
futures = "0.3.30"
flate2 = "1.0.33"
walkdir = "2.5.0"
reqwest = { version = "0.12.7", features = ["blocking"] }
zip = "2.2.0"
mpsc = "0.2.3"
anyhow = "1.0"
curl = "0.4"
wmi = "0.13.4"
sha1 = "0.10.6"
winapi = { version = "0.3.9", features = ["winnt", "processthreadsapi", "securitybaseapi", "handleapi", "sddl", "dpapi", "wincrypt"] }
num-bigint = "0.4.6"
num-traits = "0.2.19"
hex = "0.4.3"
diesel = { version = "2.2.4", features = ["sqlite", "r2d2", "64-column-tables"] }
diesel_migrations = "2.2.0"
diesel_derives = "2.2.3"
lazy_static = "1.5.0"
uuid = "1.10.0"
base64 = "0.22.1"
h2 = "0.4.6"
mio = "1.0.2"
libsqlite3-sys = { version = "0.30.1", features = ["bundled"] }
log = "0.4"
simplelog = "0.12.2"
webbrowser = "1.0.1"
eam_commons = { path = "../src-modules/eam_commons" }

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
