DROP TABLE IF EXISTS Account_Storage;
DROP TABLE IF EXISTS Equipment;
DROP TABLE IF EXISTS Account;
DROP TABLE IF EXISTS Stats;
DROP TABLE IF EXISTS ClassStats;
DROP TABLE IF EXISTS Character;
DROP TABLE IF EXISTS ItemData;
DROP TABLE IF EXISTS Pet;